api_version = "unstable"

[[extensions]]
# Change the merchant-facing name of the extension in locales/en.default.json
name = "t:title"
handle = "customer-segment-template"
type = "ui_extension"

description = "t:description"
[[extensions.targeting]]
module = "./src/CustomerSegmentTemplate.jsx"
# The target used here must match the target used in the module file (./src/CustomerSegmentTemplate.jsx)
target = "admin.customers.segmentation-templates.render"


# Valid extension points:

# - admin.customers.segmentation-templates.render
